name: coqchk

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        coq_version:
          - '8.17'
        ocaml_version: ['default']
      fail-fast: true  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          repository: 'libtx/Storage'
          path: '.deps/Storage'
      # Build the main project:
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-libtx-slot.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          before_install: |
            pwd
            find $WORKDIR
            opam pin add -n -y -k path coq-libtx-storage .deps/Storage
